// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Simulate
List Simulate(NumericVector ID_MP, NumericVector DUREE_AMORT_MOIS, NumericVector DUREE_DIFF_MOIS, NumericVector DEBUT_PRET_MOIS, NumericVector CI_ASSURE, NumericVector DIFFERE_TYPE, NumericVector TXNOM_TYPE_MENS, NumericVector TXNOM_ANN, NumericVector AGE_SOUS_ANN, NumericVector AGE_FIN_DC_ANN, NumericVector AGE_FIN_AT_ANN, NumericVector PART_H, NumericVector PART_IMMO, NumericVector PART_PERSO, NumericVector TXACTUMENS, NumericVector PRIX_PTIA_POURCDCSEUL, NumericVector ABT_AT_PERTEREV, double NombrePeriodes);
RcppExport SEXP _ModeleADE_Simulate(SEXP ID_MPSEXP, SEXP DUREE_AMORT_MOISSEXP, SEXP DUREE_DIFF_MOISSEXP, SEXP DEBUT_PRET_MOISSEXP, SEXP CI_ASSURESEXP, SEXP DIFFERE_TYPESEXP, SEXP TXNOM_TYPE_MENSSEXP, SEXP TXNOM_ANNSEXP, SEXP AGE_SOUS_ANNSEXP, SEXP AGE_FIN_DC_ANNSEXP, SEXP AGE_FIN_AT_ANNSEXP, SEXP PART_HSEXP, SEXP PART_IMMOSEXP, SEXP PART_PERSOSEXP, SEXP TXACTUMENSSEXP, SEXP PRIX_PTIA_POURCDCSEULSEXP, SEXP ABT_AT_PERTEREVSEXP, SEXP NombrePeriodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ID_MP(ID_MPSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DUREE_AMORT_MOIS(DUREE_AMORT_MOISSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DUREE_DIFF_MOIS(DUREE_DIFF_MOISSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DEBUT_PRET_MOIS(DEBUT_PRET_MOISSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CI_ASSURE(CI_ASSURESEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DIFFERE_TYPE(DIFFERE_TYPESEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TXNOM_TYPE_MENS(TXNOM_TYPE_MENSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TXNOM_ANN(TXNOM_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AGE_SOUS_ANN(AGE_SOUS_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AGE_FIN_DC_ANN(AGE_FIN_DC_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AGE_FIN_AT_ANN(AGE_FIN_AT_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PART_H(PART_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PART_IMMO(PART_IMMOSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PART_PERSO(PART_PERSOSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TXACTUMENS(TXACTUMENSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PRIX_PTIA_POURCDCSEUL(PRIX_PTIA_POURCDCSEULSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ABT_AT_PERTEREV(ABT_AT_PERTEREVSEXP);
    Rcpp::traits::input_parameter< double >::type NombrePeriodes(NombrePeriodesSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulate(ID_MP, DUREE_AMORT_MOIS, DUREE_DIFF_MOIS, DEBUT_PRET_MOIS, CI_ASSURE, DIFFERE_TYPE, TXNOM_TYPE_MENS, TXNOM_ANN, AGE_SOUS_ANN, AGE_FIN_DC_ANN, AGE_FIN_AT_ANN, PART_H, PART_IMMO, PART_PERSO, TXACTUMENS, PRIX_PTIA_POURCDCSEUL, ABT_AT_PERTEREV, NombrePeriodes));
    return rcpp_result_gen;
END_RCPP
}
// SimulateAgg
List SimulateAgg(NumericVector ID_MP, NumericVector ID_MP_AGG, NumericVector DUREE_AMORT_MOIS, NumericVector DUREE_DIFF_MOIS, NumericVector DEBUT_PRET_MOIS, NumericVector CI_ASSURE, NumericVector DIFFERE_TYPE, NumericVector TXNOM_TYPE_MENS, NumericVector TXNOM_ANN, NumericVector AGE_SOUS_ANN, NumericVector AGE_FIN_DC_ANN, NumericVector AGE_FIN_AT_ANN, NumericVector PART_H, NumericVector PART_IMMO, NumericVector PART_PERSO, NumericVector TXACTUMENS, NumericVector PRIX_PTIA_POURCDCSEUL, NumericVector ABT_AT_PERTEREV, NumericVector Periodes_AGG);
RcppExport SEXP _ModeleADE_SimulateAgg(SEXP ID_MPSEXP, SEXP ID_MP_AGGSEXP, SEXP DUREE_AMORT_MOISSEXP, SEXP DUREE_DIFF_MOISSEXP, SEXP DEBUT_PRET_MOISSEXP, SEXP CI_ASSURESEXP, SEXP DIFFERE_TYPESEXP, SEXP TXNOM_TYPE_MENSSEXP, SEXP TXNOM_ANNSEXP, SEXP AGE_SOUS_ANNSEXP, SEXP AGE_FIN_DC_ANNSEXP, SEXP AGE_FIN_AT_ANNSEXP, SEXP PART_HSEXP, SEXP PART_IMMOSEXP, SEXP PART_PERSOSEXP, SEXP TXACTUMENSSEXP, SEXP PRIX_PTIA_POURCDCSEULSEXP, SEXP ABT_AT_PERTEREVSEXP, SEXP Periodes_AGGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ID_MP(ID_MPSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ID_MP_AGG(ID_MP_AGGSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DUREE_AMORT_MOIS(DUREE_AMORT_MOISSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DUREE_DIFF_MOIS(DUREE_DIFF_MOISSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DEBUT_PRET_MOIS(DEBUT_PRET_MOISSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CI_ASSURE(CI_ASSURESEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DIFFERE_TYPE(DIFFERE_TYPESEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TXNOM_TYPE_MENS(TXNOM_TYPE_MENSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TXNOM_ANN(TXNOM_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AGE_SOUS_ANN(AGE_SOUS_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AGE_FIN_DC_ANN(AGE_FIN_DC_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AGE_FIN_AT_ANN(AGE_FIN_AT_ANNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PART_H(PART_HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PART_IMMO(PART_IMMOSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PART_PERSO(PART_PERSOSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TXACTUMENS(TXACTUMENSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PRIX_PTIA_POURCDCSEUL(PRIX_PTIA_POURCDCSEULSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ABT_AT_PERTEREV(ABT_AT_PERTEREVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Periodes_AGG(Periodes_AGGSEXP);
    rcpp_result_gen = Rcpp::wrap(SimulateAgg(ID_MP, ID_MP_AGG, DUREE_AMORT_MOIS, DUREE_DIFF_MOIS, DEBUT_PRET_MOIS, CI_ASSURE, DIFFERE_TYPE, TXNOM_TYPE_MENS, TXNOM_ANN, AGE_SOUS_ANN, AGE_FIN_DC_ANN, AGE_FIN_AT_ANN, PART_H, PART_IMMO, PART_PERSO, TXACTUMENS, PRIX_PTIA_POURCDCSEUL, ABT_AT_PERTEREV, Periodes_AGG));
    return rcpp_result_gen;
END_RCPP
}
// Setup
List Setup(NumericMatrix TableMortalite, NumericMatrix TableEntreeAT, NumericMatrix TableMaintienAT, NumericMatrix TableMaintienConstitAT);
RcppExport SEXP _ModeleADE_Setup(SEXP TableMortaliteSEXP, SEXP TableEntreeATSEXP, SEXP TableMaintienATSEXP, SEXP TableMaintienConstitATSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type TableMortalite(TableMortaliteSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type TableEntreeAT(TableEntreeATSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type TableMaintienAT(TableMaintienATSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type TableMaintienConstitAT(TableMaintienConstitATSEXP);
    rcpp_result_gen = Rcpp::wrap(Setup(TableMortalite, TableEntreeAT, TableMaintienAT, TableMaintienConstitAT));
    return rcpp_result_gen;
END_RCPP
}
// RetrieveMatrices
List RetrieveMatrices();
RcppExport SEXP _ModeleADE_RetrieveMatrices() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(RetrieveMatrices());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _ModeleADE_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ModeleADE_Simulate", (DL_FUNC) &_ModeleADE_Simulate, 18},
    {"_ModeleADE_SimulateAgg", (DL_FUNC) &_ModeleADE_SimulateAgg, 19},
    {"_ModeleADE_Setup", (DL_FUNC) &_ModeleADE_Setup, 4},
    {"_ModeleADE_RetrieveMatrices", (DL_FUNC) &_ModeleADE_RetrieveMatrices, 0},
    {"_ModeleADE_rcpp_hello_world", (DL_FUNC) &_ModeleADE_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ModeleADE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
