# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title
#' Projette les modeles points
#' @param ID_MP
#' Identifiant unique de chaque modele moint
#' @param DUREE_AMORT_MOIS 
#' Duree amortissement du pret ( en mois )
#' @param DUREE_DIFF_MOIS
#' Duree differe du pret ( en mois ) 
#' @param DEBUT_PRET_MOIS
#' Debut du pret à partir de la date de projection  ( en mois )
#' @param CI_ASSURE 
#' Capital emprunte assure ( quotite comprise )
#' @param DIFFERE_TYPE 
#' Type de differe ( 1 == Partiel , 2 == Total )
#' @param TXNOM_TYPE_MENS 
#' Type de mensualisation du taux nominal ( 1 == Proportionnel , 2 == Equivalent )
#' @param TXNOM_ANN 
#' Taux nominal du pret
#' @param AGE_SOUS_ANN 
#' Age a la souscription ( en annees )
#' @param AGE_FIN_DC_ANN 
#' Age fin de la garantie deces ( en annees )
#' @param AGE_FIN_AT_ANN 
#' Age fin  arret de travail ( en annees )
#' @param PART_H 
#' Proportion des hommes
#' @param PART_IMMO 
#' Proportion des prets immos
#' @param PART_PERSO 
#' Proportion des prets persos
#' @param TXACTUMENS 
#' Taux actualisation mensuel
#' @param PRIX_PTIA_POURCDCSEUL 
#' Prix de la PTIA
#' @param ABT_AT_PERTEREV
#' Taux abattement pour la perte de revenu 
#' @param NombrePeriodes 
#' Nombre de mois de projection
#' @return 
#' Une liste de matrices (Nombre de MP * Nombre de Periodes)
#' \item{EtatPret_EstDiffereEnCours}{indique si le prêt est dans sa periode de differe}
#' \item{EtatPret_EstEnCours}{indique si le prêt est en cours}
#' \item{Ech_CRDDebPer}{CRD de debut de periode}
#' \item{Assu_ProbSurvieCreditDebPer}{Probabilite de survie en debut de periode}
#' \item{Assu_TxMortMens}{Taux de mortalite mensuel}
#' \item{Assu_TxRAMens}{Taux de rachat mensuel}
#' \item{Res_VAN_AssietteCI}{VAN assiette  CI}
#' \item{Res_VAN_AssietteCRD}{VAN assiette CRD}
#' \item{DcPtia_VAN_Sin}{VAN sinistre DC}
#' \item{Effectif_DcPtia}{Effectif cumule DC}
#' \item{DcPtia_PrestProableDcPtia}{Prestation probable DC}
#' \item{Res_VAN_Sin_DCPTIA}{VAN Cumule sinistre DC}
#' \item{ITTIPT_VAN_Sin}{VAN sinistre AT}
#' \item{ITTIPT_TxMensEntree3Mois}{Taux mensuel entree AT}
#' \item{Effectif_ITTIPT}{Effectif cumule AT}
#' \item{Res_VAN_Sin_ITTIPT}{VAN Cumule sinistre AT}
#' @export
#' 
#' @examples
Simulate <- function(ID_MP, DUREE_AMORT_MOIS, DUREE_DIFF_MOIS, DEBUT_PRET_MOIS, CI_ASSURE, DIFFERE_TYPE, TXNOM_TYPE_MENS, TXNOM_ANN, AGE_SOUS_ANN, AGE_FIN_DC_ANN, AGE_FIN_AT_ANN, PART_H, PART_IMMO, PART_PERSO, TXACTUMENS, PRIX_PTIA_POURCDCSEUL, ABT_AT_PERTEREV, NombrePeriodes) {
    .Call(`_ModeleADE_Simulate`, ID_MP, DUREE_AMORT_MOIS, DUREE_DIFF_MOIS, DEBUT_PRET_MOIS, CI_ASSURE, DIFFERE_TYPE, TXNOM_TYPE_MENS, TXNOM_ANN, AGE_SOUS_ANN, AGE_FIN_DC_ANN, AGE_FIN_AT_ANN, PART_H, PART_IMMO, PART_PERSO, TXACTUMENS, PRIX_PTIA_POURCDCSEUL, ABT_AT_PERTEREV, NombrePeriodes)
}

#' Title
#' Projette les modeles points
#' @param ID_MP
#' Identifiant unique de chaque modele point 
#' @param ID_MP_AGG
#' Identifiant unique de chaque groupe de modele point
#' @param DUREE_AMORT_MOIS 
#' Duree amortissement du pret ( en mois )
#' @param DUREE_DIFF_MOIS
#' Duree differe du pret ( en mois ) 
#' @param DEBUT_PRET_MOIS
#' Debut du pret à partir de la date de projection  ( en mois )
#' @param CI_ASSURE 
#' Capital emprunte assure ( quotite comprise )
#' @param DIFFERE_TYPE 
#' Type de differe ( 1 == Partiel , 2 == Total )
#' @param TXNOM_TYPE_MENS 
#' Type de mensualisation du taux nominal ( 1 == Proportionnel , 2 == Equivalent )
#' @param TXNOM_ANN 
#' Taux nominal du pret
#' @param AGE_SOUS_ANN 
#' Age a la souscription ( en annees )
#' @param AGE_FIN_DC_ANN 
#' Age fin de la garantie deces ( en annees )
#' @param AGE_FIN_AT_ANN 
#' Age fin  arret de travail ( en annees )
#' @param PART_H 
#' Proportion des hommes
#' @param PART_IMMO 
#' Proportion des prets immos
#' @param PART_PERSO 
#' Proportion des prets persos
#' @param TXACTUMENS 
#' Taux actualisation mensuel
#' @param PRIX_PTIA_POURCDCSEUL 
#' Prix de la PTIA
#' @param ABT_AT_PERTEREV
#' Taux abattement pour la perte de revenu 
#' @param Periodes_AGG 
#' Nombre de mois de projection
#' @return
#' Une liste de matrices (Nombre de MP * Nombre de Periodes)
#' \item{Ech_CRDDebPer}{CRD de debut de periode}
#' \item{Assu_ProbSurvieCreditDebPer}{Probabilite de survie en debut de periode}
#' \item{Res_VAN_AssietteCI}{VAN assiette  CI}
#' \item{Res_VAN_AssietteCRD}{VAN assiette CRD}
#' \item{Res_VAN_Sin_DCPTIA}{VAN Cumule sinistre DC}
#' \item{Res_VAN_Sin_ITTIPT}{VAN Cumule sinistre AT}
#' @export
#' 
#' @examples
SimulateAgg <- function(ID_MP, ID_MP_AGG, DUREE_AMORT_MOIS, DUREE_DIFF_MOIS, DEBUT_PRET_MOIS, CI_ASSURE, DIFFERE_TYPE, TXNOM_TYPE_MENS, TXNOM_ANN, AGE_SOUS_ANN, AGE_FIN_DC_ANN, AGE_FIN_AT_ANN, PART_H, PART_IMMO, PART_PERSO, TXACTUMENS, PRIX_PTIA_POURCDCSEUL, ABT_AT_PERTEREV, Periodes_AGG) {
    .Call(`_ModeleADE_SimulateAgg`, ID_MP, ID_MP_AGG, DUREE_AMORT_MOIS, DUREE_DIFF_MOIS, DEBUT_PRET_MOIS, CI_ASSURE, DIFFERE_TYPE, TXNOM_TYPE_MENS, TXNOM_ANN, AGE_SOUS_ANN, AGE_FIN_DC_ANN, AGE_FIN_AT_ANN, PART_H, PART_IMMO, PART_PERSO, TXACTUMENS, PRIX_PTIA_POURCDCSEUL, ABT_AT_PERTEREV, Periodes_AGG)
}

#' Enregistre les differentes tables pour utilisation future par les autres fonctions
#' @param TableMortalite
#' Matrice des taux de mortalites . Cette matrice doit avoir 6 colonnes :
#' Immo_H Perso_H Pro_H Immo_F Perso_F Pro_F .Les ages vont de 18 a 90 ans.
#' @param TableEntreeAT 
#' Matrice des taux d entree en arret de travail . Cette matrice doit avoir 6 colonnes :
#' Immo_H Perso_H Pro_H Immo_F Perso_F Pro_F .Les ages vont de 18 a 67 ans.
#' @param TableMaintienAT 
#' Matrice des taux de maintien en arret de travail.
#' Il faut une franchise de 3mois sur la table
#' @param TableMaintienConstitAT 
#' Matrice des capitaux constitutifs en arret de travail.
#' Il faut une franchise de 3mois sur la table
Setup <- function(TableMortalite, TableEntreeAT, TableMaintienAT, TableMaintienConstitAT) {
    .Call(`_ModeleADE_Setup`, TableMortalite, TableEntreeAT, TableMaintienAT, TableMaintienConstitAT)
}

RetrieveMatrices <- function() {
    .Call(`_ModeleADE_RetrieveMatrices`)
}

rcpp_hello_world <- function() {
    .Call(`_ModeleADE_rcpp_hello_world`)
}

